version: "3.4"

services:
  redis:
    image: "redislabs/rejson:edge"
    hostname: redis
    container_name: skelaton-redis
    restart: on-failure
    ports:
      - "6380:6379"

  db:
    image: postgres:10.1-alpine
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    container_name: skelaton_db 
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - datadb:/var/lib/postgresql/data
      - ./files/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin123
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=skelaton_db

  mongodb:
      image: mongo:5.0
      ports:
        - 27017:27017
      volumes:
        - mongodb:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin123
        - MONGO_INITDB_ROOT_PASSWORD=admin123

volumes:
  datadb:
  mongodb:
