[app]
    name = "adsrobot"
    port = 8989

[persistent]

    [persistence.database]
        host         = "localhost"
        port         = 5432
        username     = "admin123"
        password     = "admin123"
        name         = "optimization_rule_db"
        ssl_mode     = "disable"

    [persistence.redis]
        host             = "localhost"
        port             = 6379
        password         = ""
        max_idle         = 100
        idle_timeout     = 5
        enabled          = true
        expire_time      = 60

        [persistence.redis.database]
            index           = 1

        [persistence.redis.key]
            log_activity    = "%s:log_activity:shared_session:%s"       # env:xx:xx:id
            rule_data       = "%s:%s:data:%s"                           # development:or-microservice:data:rule_id
            worker_delete   = "%s:%s:worker:delete"                     # development:cron-microservice:worker:delete
